# Place this file at .github/FUNDING.yml in each of your repos.
# It adds a "Sponsor" button to your GitHub repo page.

github: [sumitvekariya]

# Uncomment/add any others you use:
# ko_fi: yourname
# buy_me_a_coffee: yourname
# custom: ["https://your-website.com/donate"]
